version: '3.8'

services:
  hapi-fhir-stu3:
    image: hapiproject/hapi:latest
    container_name: hapi-fhir-stu3
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Xms512m -Xmx2048m
    volumes:
      - ./data:/data
      - ./config/hapi.properties:/app/WEB-INF/hapi.properties
